server:
  port: 8082

spring:
  application:
    name: fnol-intake-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: claimSubmittedEvent:com.insurtech.claims.common.events.ClaimSubmittedEvent

services:
  policy-service:
    url: ${POLICY_SERVICE_URL:http://localhost:8081}

resilience4j:
  circuitbreaker:
    instances:
      fraudCheckService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      fraudCheckService:
        maxAttempts: 3
        waitDuration: 1s

logging:
  level:
    com.insurtech.claims: DEBUG
